[package]
name = "pathfinding"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pathfinding"
path = "src/main.rs"

[dependencies]
raylib = { version = "5.5.1", features = ["wayland", "sdl"] }

[lints.rust]
unused_imports = "allow"
unused = { level = "allow", priority = -1 }
dead_code = "allow"
